[versions]
webrtc = "114.5735.08"

androidJainSipRi = "1.3.0-91"
androidx-core = "1.10.1"
androidx-lifecycle = "2.5.1"
audioswitch = "89582c47c9a04c62f90aa5e57251af4800a62c9a"
autoService = '1.0.1'
coroutines = "1.6.0"
dagger = "2.46"
groupie = "2.9.0"
junit-lib = "4.13.2"
junit-jupiter = "5.5.0"
kotlinx-serialization = "1.5.0"
lint = "30.0.1"
okhttp = "4.12.0"
protobuf = "3.22.0"
protobufJavalite = "3.22.0"
semver4j = "3.1.0"
core-ktx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"

[libraries]
android-jain-sip-ri = { module = "javax.sip:android-jain-sip-ri", version.ref = "androidJainSipRi" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
audioswitch = { module = "com.github.davidliu:audioswitch", version.ref = "audioswitch" }
dagger-lib = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupie" }
groupie-viewbinding = { module = "com.github.lisawray.groupie:groupie-viewbinding", version.ref = "groupie" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
semver4j = { module = "com.vdurmont:semver4j", version.ref = "semver4j" }
webrtc = { module = "io.github.webrtc-sdk:android-prefixed", version.ref = "webrtc" }

androidx-annotation = { module = "androidx.annotation:annotation", version = "1.6.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.1" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }
auto-service-compiler = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
coroutines-lib = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
compose-bom = "androidx.compose:compose-bom:2023.04.01"
timber = { module = "com.github.ajalt:timberkt", version = "1.5.1" }

# Lint
lint-lib = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

# Test libs
androidx-test-core = { module = "androidx.test:core", version = "1.5.0" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
junit = { module = "junit:junit", version.ref = "junit-lib" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

# Mockito 5 requires JVM 11.
#noinspection GradleDependency
mockito-core = { module = "org.mockito:mockito-core", version = "4.11.0" }
#noinspection GradleDependency
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "4.1.0" }
#noinspection GradleDependency
mockito-inline = { module = "org.mockito:mockito-inline", version = "4.11.0" }

robolectric = { module = "org.robolectric:robolectric", version = "4.11.1" }
turbine = { module = "app.cash.turbine:turbine", version = "1.0.0" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]

